# 3.2 Numpy and introduction to matrices

## Core of numpy
NumPy (Numerical Python) is a powerful library in Python for numerical computing. It provides efficient and convenient ways to work with arrays and matrices of numerical data. In this notebook, we will explore the basics of NumPy and its capabilities.

### Array Creation

An array is a fundamental data structure in NumPy. It is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. NumPy provides various functions to create arrays.

#### Creating Arrays using NumPy

To create an array using NumPy, we can use the `np.array()` function and pass a list or tuple of elements. Each element represents an item in the array.

For example:

In [1]:
import numpy as np

# Create an array using NumPy
array = np.array([1, 2, 3, 4, 5])

# Display the array
print("Array:")
print(array)

Array:
[1 2 3 4 5]


The above code creates an array with elements 1, 2, 3, 4, and 5 using the `np.array()` function.

### Array Operations

NumPy provides a wide range of operations that can be performed on arrays, including mathematical operations, indexing, slicing, and more.

#### Mathematical Operations

NumPy allows us to perform mathematical operations on arrays in an element-wise manner. These operations are performed on corresponding elements of the arrays.

For example:

In [2]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Perform element-wise addition
result = array1 + array2

# Display the result
print("\nElement-wise Addition:")
print(result)


Element-wise Addition:
[5 7 9]


The above code creates two arrays `array1` and `array2`. By using the + operator between the arrays, we perform element-wise addition. The result is a new array obtained by adding the corresponding elements of the two arrays.

#### Indexing and Slicing

NumPy arrays can be indexed and sliced to access specific elements or sub-arrays.


In [3]:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Accessing elements using indexing
print("\nElement at index 0:", array[0])
print("Element at index 3:", array[3])

# Slicing the array
print("\nSlice from index 1 to 3:", array[1:4])


Element at index 0: 1
Element at index 3: 4

Slice from index 1 to 3: [2 3 4]


In the above code, we create an array and demonstrate indexing and slicing operations. We access individual elements using indexing and obtain sub-arrays using slicing.


### Array Shape and Reshaping

NumPy provides functions to obtain the shape of an array and reshape it as needed.

#### Shape of an Array

The shape of an array refers to the dimensions of the array. It tells us the number of rows and columns or the size of each dimension in the array.

For example:

In [7]:
import numpy as np

# Create an array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape of the array
shape = array.shape

# Display the shape
print("\nShape of the array:", shape)


Shape of the array: (2, 3)


The above code creates a 2D array and uses the shape attribute to obtain its shape.

#### Reshaping an Array

NumPy allows us to reshape an array into a different shape without changing its data. This can be useful when we want to rearrange the elements of an array or convert it into a different shape.

For example:

In [ ]:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_array = array.reshape((2, 3))

# Display the reshaped array
print("\nReshaped Array:")
print(reshaped_array)

The above code creates a 1D array and reshapes it into a 2x3 matrix using the `reshape()` function.

## Matrices in numpy

Numpy provides a specialized class called ndarray to represent matrices. A matrix is a 2-dimensional array, where each element is identified by a pair of indices (row index and column index). Matrices are extensively used in various mathematical and scientific applications, including linear algebra, statistics, and machine learning.

### Creating Matrices

To create a matrix in numpy, we can use the `np.array()` function and pass a nested list or nested tuple of elements. Each inner list or tuple represents a row of the matrix. The number of elements in each row should be the same.

In [9]:
import numpy as np

# Create a matrix using NumPy
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In the above example, we create a 3x3 matrix with elements ranging from 1 to 9. The outer brackets `[ ]` represent the outer list, and the inner brackets `[ ]` represent the rows of the matrix.

### Matrix Properties

Once we have created a matrix, we can access its properties using various attributes and methods provided by numpy.

#### Shape
The shape of a matrix represents the number of rows and columns it contains. We can retrieve the shape of a matrix using the `shape` attribute.


In [ ]:
shape = matrix.shape
shape

The shape attribute returns a tuple (rows, columns).

#### Size
The size of a matrix represents the total number of elements it contains. We can retrieve the size of a matrix using the `size` attribute.

In [13]:
size = matrix.size
size

9

#### Data Type
The data type of the elements in a matrix can be obtained using the dtype attribute.

In [15]:
data_type = matrix.dtype
data_type

dtype('int64')

The dtype attribute returns the data type, such as `int64`, `float64`, etc.

### Matrix Operations

Once we have created a matrix in numpy, we can perform various operations on it, including arithmetic operations, indexing, slicing, and matrix-
specific operations like transposition and matrix multiplication.

#### Arithmetic Operations
Numpy allows us to perform arithmetic operations on matrices, such as addition, subtraction, multiplication, and division. These operations are applied element-wise.

In [18]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix addition
result = matrix1 + matrix2
result

array([[ 6,  8],
       [10, 12]])

The `result` matrix will contain the element-wise sum of `matrix1` and `matrix2`.

#### Indexing and Slicing
We can access specific elements or subsets of a matrix using indexing and slicing. Indexing refers to accessing individual elements, while slicing allows us to extract a portion of the matrix.

In [21]:
import numpy as np

# Access a specific element
element = matrix[0, 0]

# Extract a subset of the matrix
subset = matrix[1:3, 1:3]
subset

array([[5, 6],
       [8, 9]])

In the above example, we access the element at the first row and first column using indexing. We also extract a subset of the matrix using slicing, which includes rows 1 and 2 and columns 1 and 2.

#### Matrix Transposition
Transposing a matrix means interchanging its rows with columns. Numpy provides the `transpose()` function to perform matrix transposition.

In [23]:
import numpy as np

# Transpose a matrix
transposed_matrix = np.transpose(matrix)
transposed_matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

The transposed_matrix will contain the transposed form of the original matrix.

#### Matrix Multiplication
Numpy provides the `@` operator or the `dot()` function to perform matrix multiplication.

In [25]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = matrix1 @ matrix2
result

array([[19, 22],
       [43, 50]])

The result matrix will contain the product of matrix1 and matrix2 obtained through matrix multiplication.